apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      affinity: {}
      containers:
        - image: "941377120724.dkr.ecr.us-east-1.amazonaws.com/billeasy-frontend:{{ .Values.image.imagetag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          name: {{ .Release.Name }}
          env:
            - name: REACT_APP_BACKEND_URL
              value: "http:abcacfb2932944bf4a6f122ed8b8df19-144775867.us-east-1.elb.amazonaws.com:31225/api/tasks"
          ports:
            - containerPort: {{ .Values.service.port }}
              name: tcp
              protocol: TCP
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      restartPolicy: Always
