apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-clusterip
  labels:
    app: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: frontend
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Release.Name }}